### ISSUE TITLE
安装是缺少了git包，是否还没有公开？

### ISSUE THREAD

**Issue by GithubOfAiwen** [WildDogTeam/liveshell#1]
在执行命令：git submodule update --init --recursive时候发生的

fatal: Authentication failed for 'https://github.com/WildDogTeam/wilddog_client_coap.git/'

**Comment by itolfh** [comment]
@GithubOfAiwen 更换了git源，但是没有及时push到master上，sorry，重新clone一版就好了

**Comment by itolfh** [comment]
很久没有回复，关闭issue。
